# Generated by Django 5.2.1 on 2026-08-16 21:30

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_examination_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='upload_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/applications/', validators=[applications.models.validate_file_extension_and_size]),
        ),
    ]
