# Generated by Django 6.0.4 on 2026-06-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionround',
            name='is_allocated',
            field=models.BooleanField(default=False),
        ),
    ]
