# Generated by Django 5.2.1 on 2026-06-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_remove_application_school_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='examination_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
