# Generated by Django 5.2.1 on 2026-09-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_upload_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_faculty_child',
            field=models.CharField(choices=[('yes', 'نعم'), ('no', 'كلا')], default='no', max_length=5, verbose_name='هل انت من ابناء التدريسين'),
        ),
    ]
