# Generated by Django 5.2.1 on 2026-09-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_is_faculty_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='graduation_attempt',
            field=models.CharField(choices=[('first_round', 'الدور الأول'), ('second_round', 'الدور الثاني'), ('third_round', 'الدور الثالث')], default='first_round', max_length=20, verbose_name='دور التخرج'),
        ),
    ]
