# Generated by Django 5.2.1 on 2026-09-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_application_graduation_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='original_total_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='المجموع الأصلي (قبل الإضافة)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='المجموع الكلي النهائي (بعد الإضافة)'),
        ),
    ]
