# Generated by Django 5.2.1 on 2026-09-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_application_original_total_sum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='french_degree',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درجة اللغة الفرنسية'),
        ),
        migrations.AddField(
            model_name='application',
            name='has_french_language',
            field=models.CharField(choices=[('yes', 'نعم'), ('no', 'كلا')], default='no', max_length=5, verbose_name='هل لديك لغة فرنسية'),
        ),
    ]
