# Generated by Django 5.2.1 on 2026-09-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_application_french_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='graduation_date',
            field=models.CharField(max_length=9, verbose_name='سنة التخرج'),
        ),
    ]
