# Generated by Django 5.2.1 on 2026-09-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_alter_graduation_date_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='average',
            field=models.DecimalField(db_index=True, decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='application',
            name='original_total_sum',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='المجموع الأصلي (قبل الإضافة)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='total_sum',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='المجموع الكلي النهائي (بعد الإضافة)'),
        ),
    ]
