# Generated by Django 5.2.1 on 2026-09-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_alter_application_average_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='number_of_lessons',
            field=models.PositiveIntegerField(choices=[(5, '5 دروس'), (6, '6 دروس'), (7, '7 دروس')], default=7, verbose_name='عدد الدروس'),
        ),
    ]
