# Generated by Django 5.2.1 on 2026-09-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_alter_application_number_of_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='french_degree',
        ),
        migrations.RemoveField(
            model_name='application',
            name='has_french_language',
        ),
        migrations.AddField(
            model_name='application',
            name='added_language',
            field=models.CharField(choices=[('none', 'لا يوجد'), ('french', 'اللغة الفرنسية'), ('turkish', 'اللغة التركية')], default='none', max_length=10, verbose_name='اللغات المضافة'),
        ),
        migrations.AddField(
            model_name='application',
            name='added_language_degree',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درجة اللغة المضافة'),
        ),
    ]
