# Generated by Django 5.2.1 on 2026-09-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_remove_application_french_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='added_language',
            field=models.CharField(blank=True, choices=[('none', 'لا يوجد'), ('french', 'اللغة الفرنسية'), ('turkish', 'اللغة التركية')], default='none', max_length=10, verbose_name='اللغات المضافة'),
        ),
    ]
