# Generated by Django 5.2.1 on 2026-09-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_alter_application_added_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='added_language',
            field=models.CharField(choices=[('none', 'لا يوجد'), ('french', 'اللغة الفرنسية'), ('turkish', 'اللغة التركية')], default='none', max_length=10, verbose_name='اللغات المضافة'),
        ),
    ]
